# Generated by Django 4.1.4 on 2022-12-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TrendQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('protection_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.protectionlevel')),
            ],
        ),
    ]
